name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 6 * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          USERNAME: artdelpi
          BRANCH_NAME: "main"
          UTC_OFFSET: -3
          EXCLUDE: "Jupyter Notebook,jupyter Notebook"
          AUTO_PUSH: true
